### ISSUE TITLE
Stores are unexpectedly invalidated when subscriber count drops to 0 and goes up to 1

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#670] opened 2021-09-17 13:55 UTC
This is a low urgency problem. More like something to digest concerning frontend reactivity.

In [this PR](https://github.com/centerofci/mathesar/pull/627#issuecomment-917023226) we ran into a bug where a derived store was calling its update/invalidation callback even though the stores derived by that store had not updated. It turns out that this is intended behaviour when the number of subscriber drops to 0, and goes up to 1: i.e. a new "first" subscriber appears. More details can be found on [this](https://github.com/sveltejs/svelte/issues/6724) Svelte's issue thread.

I see two viable solutions. To use dummy subscriptions on stores that we don't want to be invalidated by "new-first" subscribers, or to do a more thorough rethink of how we implement stores.

Another option could be to track our subscriptions and unsubscriptions and make sure the subscriber count never goes to 0 and then to 1, but that's a bad idea since we don't want to bring this concern into the component logic (components cause un/subscriptions).

A dummy subscription looks like this: `readable.subscribe(() => {});`. You put it top-level in a module and it subscribes when the module is first evaluated (imported) and stays subscribed for the duration of the application's runtime. It's dirty, since we're treating the symptom, but it's easy to understand (combined with an indepth comment), isolated and very low effort.

A rethink of stores might make sense long-term. Svelte stores, as far as I can tell, are modelled on RxJS [`BehaviorSubject`](https://rxjs.dev/guide/subject), but RxJS's ecosystem can compose `BehaviourSubject` with operators `distinctUntilChanged` and `shareReplay` to make it behave like we want it to (see this REPL [session](https://svelte.dev/repl/c872db70aba84a1bb61f431e84040b8d?version=3.42.6)), while the Svelte store is stuck being what it is :).

Svelte's reactive functionality is compatible with RxJS (Svelte store dereference syntax works out-of-the-box and the assignment syntax support can be implemented with a minor wrapper on the RxJS `BehaviorSubject`), so migrating to RxJS would not be complicated. Downsides of RxJS is that it might seem daunting at first to those unfamiliar. Upside is that it's more mature and more powerful.

Switching stores to RxJS doesn't seem to make much sense at the moment, since the problem in question is easy to workaround. But, it's a good option to keep in mind. If the codebase ever needs more interesting reactive logic, that might be the incentive needed to make the migration.

**Comment by pavish** [comment] 2021-09-17 15:32
@dmos62 The workaround we are looking at, to have a dummy subscription requires more thought. This would always keep the stores active, which inturn may result in a memory leak.

In our case, the table-data related stores are created dynamically. It is essential that each instance of the dynamic stores get garbage collected when they are no longer required. If we create a dummy subscription, it will hold a reference to the store which will lead it to be kept in the memory. We could manually unsubscribe when we remove all references to the table-data object, but that will lead to more boilerplate code.

I think the behaviour of svelte's derived/readable stores are quite clear, and we have to be aware of it during development and review.

In our particular case, the most optimal solution is to cache the response. WRT https://github.com/centerofci/mathesar/pull/627, we could cache the types response per database, in the db store layer, instead of fixating on having an api call within a store callback. Moving the api call away from within the callback resolves this.

I do agree that a svelte store interface over RxJS seems like a good alternative, but it's premature to switch at this point. We can keep this issue open, until we have a more compelling reason to use RxJS.

**Comment by dmos62** [comment] 2021-09-17 16:20
@dmos62 I propose to only apply dummy subscriptions to stores that are singleton across the app, and that do suffer from erronious invalidations, like `currentDBMathesarTypes`. In the case of this store garbage collection is irrelevant. Maybe most problematic stores will be like this.

The problem with explicit caching is that it adds conflicts to the reactive model. Part of the role of the state store is to cache. To implement a cache alongside it is to effectively reimplement the store (or to implement two stores connected in series).

I would be in favor of a better store implementation, but in that case RxJS route is more prudent, in my opinion. It would result in a cleaner reactive model (state more centralized). We'd also be using a mature library, instead of spinning our own solution.

**Comment by pavish** [comment] 2021-09-19 13:02
@dmos62 We have additional caching for a separate purpose. If you noticed some top level stores, you could find that data is preloaded initially through django templates instead of making an API call. This is an optimization to render the pages as fast as possible without additional network calls during initial load. The plan is to eventually have it for all top level stores.

Also, we have support for switching across databases and schemas and it makes sense to cache the data of the entities that have already been visited, since they rarely change. This data is stored in plain module level maps instead of stores, since they do not require reactivity.

The only portion that utilize stores are those that require reactivity i.e. the ones used by the view layer, namely the list of currently visible entities. The `currentDBMathesarTypes` depends on the currently selected database. This data will be preloaded on initial load, and the api call is only made the first time the user visits a different db, which is then cached.

I was suggesting caching the types considering all of these requirements. We could use RxJS to resolve the issue mentioned earlier but we would still need to perform additional caching over it to satisfy the above usecases. The additional caching takes away the need for the derived stores to make api calls from within them, so the issue mentioned earlier wouldn't be applicable anymore.

Having said all of this, I do agree that RxJS is more prudent but switching at the moment is premature, considering it increases the bundle size of around ~30kb, and the additional size is not worth the benefit.

**Comment by dmos62** [comment] 2021-09-20 08:46
I won't be pushing the point, but for the sake of completeness I'll list some points of conflict between our points of view.

RxJS is capable of handling all state while staying fully within its intended operating scope. The preloaded data can be a subscribable.

I do not think that a bundle size gain of such magnitude over improved state management is a good compromise. I am impressed by the willingness to go a long way to reduce bandwidth use and load times, but non-simple state management might compromise ability to extend and maintain the system.

**Comment by pavish** [comment] 2021-09-20 10:27
@dmos62 I really appreciate all the points and thought you've put forward in this conversation. They make perfect sense considering long term maintainability of the project. I would have been inclined to go with it if it had a smaller impact on end user experience.

As mentioned earlier, I'd still like to keep this issue open and labelled status:future, and we could circle back to it when the code base around the top level stores grow.

**Comment by seancolsen** [comment] 2023-01-23 20:19
I'm doing a little ticket clean up and I'm closing this issue because I don't see anything actionable here. If we can identify an issue with our pattern usage of stores that leads to a more concrete and clearly reproducible bug, then I'd be inclined to subject our patterns to more scrutiny. I'd be happy to re-open this ticket if someone wants to propose a specific change or demonstrate a specific problem

**Closed by seancolsen** 2023-01-23 20:19 UTC
Labels: type: bug, affects: technical debt, work: frontend, priority: future
