### ISSUE TITLE
FK column names need link icon in some UI locations

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2355] opened 2023-01-24 22:15 UTC
## Good

These places in the UI show a link icon for an FK column. That's good.

![image](https://user-images.githubusercontent.com/42411/214428047-1224e54f-5229-43be-8284-dcf8014ec1fb.png)

![image](https://user-images.githubusercontent.com/42411/214429056-289ed628-632b-4c34-94a3-4b01d942a49a.png)

![image](https://user-images.githubusercontent.com/42411/214429438-99b73270-a6db-4030-9901-e53c6871f576.png)

## Bad

These places show that same column, but they have the wrong icon. They're showing the icon for the column's _type_, but they don't take the FK into account. We should change these places to show the correct icon.

![image](https://user-images.githubusercontent.com/42411/214433017-6c953d56-57f4-48de-b306-345f1d6d3233.png)

![image](https://user-images.githubusercontent.com/42411/214433187-c59b21a2-c5ce-439f-8d11-40b403395af6.png)

![image](https://user-images.githubusercontent.com/42411/214432450-854bf9e9-d059-441a-8be1-4954322ff477.png)

![image](https://user-images.githubusercontent.com/42411/214432547-f819963a-0eab-49bc-8563-3264f3dd36dc.png)

![image](https://user-images.githubusercontent.com/42411/214426251-c2f1fea8-4915-4f82-a6cf-5ab9074b26c4.png)

![image](https://user-images.githubusercontent.com/42411/214428314-05a27e79-48bc-4181-97e3-5b2e44c52eae.png)

![image](https://user-images.githubusercontent.com/42411/214428791-19b4d08a-bace-484c-a914-533794562008.png)

## Implementation notes

- At first glace, this issue may appear rather trivial, but it's not. This is not a matter of swapping out one icon for another. Due to some complex requirements from the Data Explorer, column objects are somewhat polymorphic, which is part of what makes this icon work a little tricky and bug-prone.

- The `ColumnName.svelte` component receives a `DisplayColumn`, but several other types are able to satisfy `DisplayColumn`. The `ProcessedColumn` type is the one that will have sufficient info to render the correct icon. We need to go looking through usages of `ColumnName.svelte` and try to get the value supplied to its `column` prop to have a `constraintsType` property. If you can feed in a `ProcessedColumn` object then that will do the trick. But if that's tough then you might be able to compute a `constraintsType` property and tack that onto whatever is already being passed in.

- Notice how we have `SelectProcessedColumns.svelte`. That's good because it always accepts a `ProcessedColumn` object (which will have the correct icon). For single-select, we have `SelectColumn.svelte`. It might be a good idea to make a new component `SelectProcessedColumn.svelte` (which is a single-select for `ProcessedColumn` objects) and use that instead of `SelectColumn` where possible.

**Comment by varun7singh** [comment] 2023-02-18 10:26
Hi @seancolsen can i work on this issue

**Comment by Anish9901** [comment] 2023-02-18 20:07
Assigned to you @varun7singh. Thanks!

**Comment by Anish9901** [comment] 2023-02-28 14:33
Unassigned due to inactivity.

**Comment by varun7singh** [comment] 2023-02-28 15:29
hi @Anish9901 i was working on this can i continue working on this? Thanks.

**Comment by Anish9901** [comment] 2023-02-28 15:38
Feel free to open a PR @varun7singh and I'll reassign you if someone doesn't comes up with the fix/PR in the meantime.

**Comment by varun7singh** [comment] 2023-02-28 19:08
Hi @Anish9901 should i just replace the SelectColumn component with a new SelectProcessedColumn and if so can i get some help?

**Comment by Anish9901** [comment] 2023-03-01 11:14
@varun7singh can you ask your query on the [Frontend channel](https://matrix.to/#/#frontend:matrix.mathesar.org). Someone there can help you better with your issue.

**Comment by Hatilar420** [comment] 2023-03-03 08:42
Hi @Anish9901 can i work on this if no is assigned ?

**Comment by Anish9901** [comment] 2023-03-03 10:15
Feel free to open a PR @Hatilar420 or @varun7singh

**Comment by hemant-hc** [comment] 2023-03-05 12:38
Hello @Anish9901 can I work on this issue?

**Comment by hemant-hc** [comment] 2023-03-08 11:47
@Anish9901 I was trying to reproduce this issue and have made some progress towards the solution as well but I wanted to validate my approach first. Is it ok if I create a draft PR here?

**Comment by seancolsen** [comment] 2023-03-08 11:48
@hemant-hc yes, please open a draft PR and tag me in a comment requesting that I review it.

**Comment by hemant-hc** [comment] 2023-03-08 13:53
Hi @seancolsen can you review this please.

**Comment by monstajoe2002** [comment] 2023-03-12 17:21
Hello @seancolsen can you please assign this issue to me?

**Comment by seancolsen** [comment] 2023-03-13 12:26
@monstajoe2002, let's wait until the PR #2650 is resolved before moving forward with more work on this ticket.

**Comment by monstajoe2002** [comment] 2023-03-13 12:44
Can I resolve that in the meantime?

**Comment by monstajoe2002** [comment] 2023-03-13 12:46
Can I resolve that in the meantime?

**Comment by seancolsen** [comment] 2023-03-13 13:34
@monstajoe2002, no, that PR is for me to review

**Comment by hemant-hc** [comment] 2023-03-27 09:22
Hi, @seancolsen. I am sorry for the late response. Thanks for reviewing my draft PR and suggesting fixes. I have implemented the fix you suggested to this PR. This PR fixes some parts of the issues. I will address the remaining parts of the issue in the next PR. Can you please review this PR for me.

**Comment by seancolsen** [comment] 2023-03-28 15:41
## Status update

Some of these issues have been fixed in #2750.

The following problems still remain:

![image](https://user-images.githubusercontent.com/42411/214426251-c2f1fea8-4915-4f82-a6cf-5ab9074b26c4.png)

![image](https://user-images.githubusercontent.com/42411/214428314-05a27e79-48bc-4181-97e3-5b2e44c52eae.png)

![image](https://user-images.githubusercontent.com/42411/214428791-19b4d08a-bace-484c-a914-533794562008.png)

**Comment by seancolsen** [comment] 2023-03-28 15:44
I am keeping @hemant-hc assigned to this issue because of this [comment](https://github.com/centerofci/mathesar/pull/2750#issuecomment-1486992273)

> I will take it up in a subsequent PR.

@hemant-hc note that we don't require any changes within the Data Explorer. See the screenshots above to make sure you understand the remaining work. If you don't plan to continue working on the remaining problems, then you can unassign yourself from the issue.

**Closed** 2023-04-19 00:52 UTC
Labels: type: enhancement, help wanted, work: frontend, status: ready
