### ISSUE TITLE
Display options for boolean not saved in staging env, contains invalid entries

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1296] opened 2022-04-19 04:30 UTC
## Description
* Open 'Movies' table in staging
* Notice that we have a boolean column named 'Watched'
* Change Display options of the boolean column to dropdown and with custom labels
* Save the column, notice that the request is sent as expected and the response is received as expected.
  Request:
  ```json
  {
    "type":"BOOLEAN",
    "type_options":{},
    "display_options": {
      "input":"dropdown",
      "custom_labels": {
        "TRUE":"true",
        "FALSE":"false"
      }
    }
  }
  ```
  Response:
  ```json
  {
    "id":53,
    "name":"Watched",
    "type":"BOOLEAN",
    "type_options":null,
    "display_options": {
      "input":"dropdown",
      "custom_labels":{"TRUE":"true","FALSE":"false"}
    },
    "nullable":true,
    "primary_key":false,
    "valid_target_types":["..."],
    "default":null
  }
  ```
* A subsequent request to fetch all columns is sent.
* Notice that the response here contains invalid entry `show_as_percentage`.
  ```json
  {
    "count":4,
    "results":[
      "...",
      {
        "id":53,
        "name":"Watched",
        "type":"BOOLEAN",
        "type_options":null,
        "display_options":{"show_as_percentage": false},
        "nullable":true,
        "primary_key":false,
        "valid_target_types":["..."],
        "default":null
      }
    ]
  }
  ```

## Expected behavior
The display options should get saved as expected and should not contain invalid entries.

**Comment by kid-116** [comment] 2022-04-19 19:36
Could I take up this issue?

**Comment by kgodey** [comment] 2022-04-19 22:33
Sure, go ahead @kid-116. 

Since this is in our current milestone, this is pretty high priority.  Someone from the core team will probably take this over if there's no PR within a few days.

**Comment by kid-116** [comment] 2022-04-20 15:40
I'm not able to reproduce this locally. I'll unassign myself.

**Comment by kgodey** [comment] 2022-05-04 16:31
I cannot reproduce this any longer. We've had several display options fixes merged in the last few days, so I assume it was fixed in one of them. Closing.

**Closed by kgodey** 2022-05-04 16:31 UTC
Labels: type: bug, work: backend, status: started
