### ISSUE TITLE
Change helpText from prop to slot in NameAndDescInputModalForm

### ISSUE THREAD

**Issue by rajatvijay** [centerofci/mathesar#1858] opened 2022-10-21 09:17 UTC
`helpText` would work better as a slot than as a prop. I see in the parent component you're passing a huge string into this prop. If you use a slot, you'll be able to move that text out of a string and put it directly into the template. This also makes it possible to put formatting in the help text. 

File: `mathesar_ui/src/components/NameAndDescInputModalForm.svelte`

_Originally posted by @seancolsen in https://github.com/centerofci/mathesar/pull/1793#discussion_r997418631_

**Comment by KAIMonmoy** [comment] 2022-11-03 18:10
I would like to work on it, if it is still open. @rajatvijay could you please assign this to me?

**Comment by seancolsen** [comment] 2022-11-03 18:26
@KAIMonmoy Thanks! Feel free to start work on this ticket and submit a PR when you're ready. We are non longer marking external contributors as officially "assigned" to tickets though because it's been challenging managing the people who don't follow through.

**Comment by KAIMonmoy** [comment] 2022-11-03 20:38
Thank you for your response, @seancolsen. I'll start working on this ticket.
It might take some time as I'm quite new to open-source contribution 😅. But I'll definitely try my best.

**Comment by KAIMonmoy** [comment] 2022-11-04 15:39
Hey @seancolsen ,
I don't think converting from helpText from prop to slot.

Because when we're passing helpText as a prop we can conditionally render the Alert Component in File: ```mathesar_ui/src/components/NameAndDescInputModalForm.svelte```

But when we are passing helpText as a slot, we'll have to update the code in File: ```mathesar_ui/src/components/NameAndDescInputModalForm.svelte``` like below -
```diff
- {#if helpText}
-   <Alert appearance="info">
-     <slot slot="content">{helpText}</slot>
-   </Alert>
- {/if}
+ {#if $$slots.helpText}
+   <Alert appearance="info">
+     <slot name="helpText" slot="content" />
+   </Alert>
+ {/if}
```
But now in order to make it work properply we'll have to change the code in File: ```mathesar_ui/src/pages/database/AddEditSchemaModal.svelte``` like below -
```diff
  saveButtonLabel={schema ? 'Save' : 'Create New Schema'}
-  helpText={schema ? '' : createSchemaHelpText}
 >

+  {#if !schema}
+    <svelte:fragment slot="helpText">{createSchemaHelpText}</svelte:fragment>
+  {/if}
```
But the problem is we cannot have a ```slotted component``` inside an ```if```.

I can think of two solutions to overcome this issue.

(1) Taking the Alert component to File - ```mathesar_ui/src/pages/database/AddEditSchemaModal.svelte``` and using a slot to render it in File - ```mathesar_ui/src/components/NameAndDescInputModalForm.svelte```
```diff
// mathesar_ui/src/components/NameAndDescInputModalForm.svelte

- {#if helpText}
-   <Alert appearance="info">
-     <slot slot="content">{helpText}</slot>
-   </Alert>
- {/if}
+ {#if $$slots.helpText}
+   <Alert appearance="info">
+     <slot name="helpText" slot="content" />
+   </Alert>
+ {/if}
```
```diff
// mathesar_ui/src/pages/database/AddEditSchemaModal.svelte

- import type { ModalController } from '@mathesar-component-library';
+ import { Alert, ModalController } from '@mathesar-component-library';
  
...

 saveButtonLabel={schema ? 'Save' : 'Create New Schema'}
-  helpText={schema ? '' : createSchemaHelpText}
 >

...

   {#if schema}
      Rename <Identifier>{initialName}</Identifier> Schema
   {:else}
     Create Schema
+     <Alert appearance="info" slot="helpText">
+        <span slot="content">{createSchemaHelpText}</span>
+     </Alert>
   {/if}
```
(2) We can extract out Alert along with the helpText slot and make it into a component called NameAndDescInputModalFormHelp text. And use that in place of the Alert component in File - ```mathesar_ui/src/pages/database/AddEditSchemaModal.svelte```

Let me know which one you prefer. And also if you think I am missing something or there are other ways to solve this problem, please share those with me.

**Comment by KAIMonmoy** [comment] 2022-11-04 15:56
One more thing, which one do you think looks better?

1. ![image](https://user-images.githubusercontent.com/33915686/200019632-3fbb51b5-bc7b-4bce-8a11-f1aad2e7852c.png)
2. ![image](https://user-images.githubusercontent.com/33915686/200020303-4446e91c-e431-4be6-9c42-0bb7b041bd69.png)

**Comment by seancolsen** [comment] 2022-11-04 18:19
Ugh. You've run into https://github.com/sveltejs/svelte/issues/5604. I've hit this before and it's annoying. 

Here's the way I'd like to fix this...

- In `NameAndDescInputModalForm.svelte` we should have only

    ```svelte
    <slot name="helpText" />
    ```

    (We should should _not_ be rendering `Alert`.)

- Also, in `Alert.svelte`, we should should change `<slot name="content" />` to `<slot />` because there is only one slot. We'll need to update the other reference to this component too.

- Then in `AddEditSchemaModal.svelte`, we should have:

    ```svelte
    <svelte:fragment slot="helpText">
      {#if !schema}
        <Alert appearance="info">
          Name your schema to reflect its purpose. For example, your personal
          financial schema may be called "Personal Finances" and your movie
          collection "Movies." Add a description to your schema to remember what
          it's for.
        </Alert>
      {/if}
    </svelte:fragment>
    ```

That should do the trick. You shouldn't need to mess with the position of the light bulb in `Alert.svelte`.

**Comment by KAIMonmoy** [comment] 2022-11-05 10:49
@seancolsen I have opened a PR-[1903](https://github.com/centerofci/mathesar/pull/1903). That should close fix/close this issue. Thanks for all the help.

**Closed** 2022-11-07 14:48 UTC
Labels: type: enhancement, good first issue, help wanted, work: frontend, status: ready
