### ISSUE TITLE
Add support for suggesting display options

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#1207] opened 2022-03-21 19:23 UTC
## Problem
When data is imported, we infer the data and suggest certain column options instead of user having to do the manual work. We use `tables/type_suggestions` endpoint  for it.

`tables/type_suggestions` endpoint supports suggesting column `types` only, there are few display options that can be inferred from the imported data, so we should also support suggesting column `display options` as part of the `type_suggestions` endpoint.

## Proposed solution
`tables/type_suggestions` endpoint should infer display options for the inferred column types and return the inferred display options along with inferred column `types`

## Additional Context
- Blocked by design work #1227 
- This feature is an enhancement for #1205.

**Comment by mathemancer** [comment] 2022-03-22 12:47
Doesn't this need more fleshing out? What's the intended behavior if we encounter a column with more than one currency symbol? Or with some integers and some values with a decimal point?

**Comment by seancolsen** [comment] 2022-03-22 13:09
I'm responding here to a [Matrix thread](https://matrix.to/#/!vAyoAQoixqNrvBuIcH:matrix.mathesar.org/$KHW3qcC1mkztCofbpDbtmwFmz_Ljj6yjKpWs8fHBYmo?via=matrix.mathesar.org&via=matrix.org).

I agree with @silentninja  in that I think it's important for us to infer the currency unit during import. If the column contains multiple currency units that should be an error. I can appreciate that it may be difficult to implement that, given that the importer can't see multiple rows at once (though I know very little about those implementation details). But I do think that it's important to get this right. The currency unit is not just display. It's data.

**Comment by silentninja** [comment] 2022-03-22 13:19
@seancolsen @mathemancer I moved the conversation to #1105 as it is a better place to track money type display options information.

**Comment by mathemancer** [comment] 2022-03-22 13:25
> The currency unit is not just display.

If we come to an agreement on that, then we shouldn't be storing it as a display option at all.
- It's not actually stored in the user database
- It's not visible anywhere except Mathesar (e.g., through other clients)
- If we create a new column and copy the data, we now need to get the type, data and display options correct.
- If we create a foreign key column, we're now required to make decisions about syncing up display options.
  - What about list aggregations? Do we somehow pass display options through?

And so on. Display options are _not_ an appropriate place to hold data.

**Comment by pavish** [comment] 2022-03-22 13:30
> If we come to an agreement on that, then we shouldn't be storing it (currency unit) as a display option at all.
> Display options are not an appropriate place to hold data.

I agree with this, and I think we should make the currency unit a database option.

Unrelated, I still see value in having a mathesar ui specific endpoint that can suggest display options as I mentioned in my previous comment. But this is not at all a priority and can be taken up for future consideration.

**Comment by silentninja** [comment] 2022-03-22 17:43
> we just need to save them to the Django column model.

When should we do that? The current workflow is something like 

(1) Import data -> (2) Get type suggestion -> (3) Preview the data with suggested type -> (4) Make changes to incorrect suggestions if any -> (5) Update the table with the changes

**Comment by kgodey** [comment] 2022-03-22 20:32
> It would be a bad UX IMO as it could end up confusing the user if the inferred data is incorrect

I agree, I do think we need to handle this before our first release. I thought we could wait to handle this portion of the task until we have an updated design for the import page (with display options). The new design might result in new backend requirements.

My point was that I don't think it's a blocker for #1105, just an additional feature after #1105 is complete.

**Comment by mathemancer** [comment] 2022-03-23 02:19
> If we save them directly, there wouldn't be a way to override the display options. User would have to complete the import process and then make changes to display options. It would be a bad UX IMO as it could end up confusing the user if the inferred data is incorrect

I think it's better that dealing with display options is a separate step. It's important that the user understands what data was actually imported, and how. The display used during the "confirm import" needs to be as close as possible to what's in the database, while avoiding ambiguity. For example, when showing them dates they've imported, it might be best to show them in `YYYY-MM-DD` format, _with a key describing the format_, since there may be some dates where the day and month are backwards from what they expect. It's crucial that they notice that problem and address it at that point. If we're fiddling around with switching the day and month order based on what we infer, it reduces consistency and (under some conditions) actually makes it impossible for the user to verify that day and month numbers were imported to the correct places.

I strongly recommend against changing the display of imported data based on some black-box (to the user) inference at any point where they're supposed to be verifying its correctness.

**Comment by kgodey** [comment] 2022-03-24 15:42
@silentninja Can you create a design issue for showing display options in the preview page and mark the related backend issues as blocked on it? Make sure to include all the design concerns raised in the discussions.

**Comment by silentninja** [comment] 2022-03-24 16:08
@kgodey Sure, I will do it.

**Comment by kgodey** [comment] 2022-09-28 16:03
I don't think we need this, closing.

**Closed by kgodey** 2022-09-28 16:03 UTC
Labels: type: enhancement, work: backend, status: blocked
