### ISSUE TITLE
Change in Behaviour of Sorting, Filtering, Grouping and Copy-Paste for Linked Records

### ISSUE THREAD

**Issue by ghislaineguerin** [centerofci/mathesar#3080] opened 2023-07-20 22:03 UTC
## Description

Up until recently, sorting, filtering, and grouping operations were performed based on the content of the linked records in a table, not the key or the ID number. Also, when I copied cells containing linked records, the copied content was the actual text displayed on the table, not the keys. However, this behaviour has changed recently. Now, these operations are based on the keys or ID numbers, not the content of the linked records. Therefore, I am unable to sort these records alphabetically for review, which was possible before.

## Expected behavior

The expected behavior is that sorting, filtering, and grouping operations should work on the content of the linked records, not the keys or the ID numbers. (It might be acceptable to have both, but that might require design)
Also, when copying cells with linked records, the actual text displayed on the table should be copied, not the keys.

## To Reproduce

1. Create a table with linked records.
2. Try to sort, filter, or group these linked records.
3. Note that these operations are performed on the keys or ID numbers, not the content of the linked records.
4. Now, copy a cell with a linked record and paste it.
5. Observe that the copied content is the key, not the actual text displayed on the table.

**Comment by seancolsen** [comment] 2023-07-21 12:16
@ghislaineguerin Thanks for raising this issue. You mention four separate things which I think warrant four separate discussions. As such, I'm closing this ticket in favor of some more focused tickets linked below.

## Copy-paste

**We do have a regression here.**

I've opened #3085 to track it, and assigned it to myself. We can continue discussion there. This will likely be a very quick fix.

## Sorting

I agree there is a problem here, and I've opened #3084 to track it. But this will be much more difficult to address. There are some design questions in that ticket, and we continue discussion there.

Also you say:

> I am unable to sort these records alphabetically for review, _which was possible before_.

(emphasis added)

If this behavior has ever _changed_, I would be very surprised. Any additional detail you might be able to recall about how this behavior has changed might be helpful. Please post in that ticket if you are able to recall more.

My guess is that, because copy-paste behavior _has_ changed, you may have inadvertently concluded that the sorting behavior has changed too.

## Filtering and grouping

You mention filtering in the ticket description. Can you clarify the difference in your **expected behavior** vs your **observed behavior**? Filtering seems to work smoothly for me.

![image](https://github.com/centerofci/mathesar/assets/42411/bb26e702-8d98-4645-8f43-d0f453078718)

Grouping also seems to work smoothly for me. Any clarification you could give would be helpful.

![image](https://github.com/centerofci/mathesar/assets/42411/0b402f54-e6a1-4bbf-aa49-fbb7b68e48ab)

I'm going to take a guess that you may have inadvertently lumped filtering and grouping into this ticket. As such I have not opened any separate tickets to track issues with this behavior. If you're still observing a problem, then please open a ticket which describes that problem in more detail.

**Closed by seancolsen** 2023-07-21 12:16 UTC
Labels: type: bug, status: triage
