### ISSUE TITLE
Incorrect icon color for public schema in breadcrumb

### ISSUE THREAD

**Issue by ghislaineguerin** [centerofci/mathesar#2159] opened 2022-12-22 14:30 UTC
### Problem
Icon colors in breadcrumb are being overwritten by a specific rule, causing incorrect colors to be displayed. The overwrite is being applied to locked schemas (e.g. public).

### Expected behavior
Icon colors in breadcrumb should display correctly and should not be affected by any overwriting rules.

### Screenshot
<img width="573" alt="image" src="https://user-images.githubusercontent.com/845767/209155505-6748a408-f835-47bd-9801-3beb5fce1733.png">

**Comment by seancolsen** [comment] 2022-12-22 15:27
Duplicate of #2109

**Closed by seancolsen** 2022-12-22 15:27 UTC
Labels: type: bug, work: frontend, status: ready
