### ISSUE TITLE
Load test our live demo

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2452] opened 2023-02-10 17:43 UTC
## Problem

We should make sure our live demo server can handle 500-1000 concurrent users.

## Proposed solution

- [ ] Set up https://locust.io/
- [ ] Write some load tests that simulate API usage for common activities (logging in, creating schemas, table actions, etc.)
- [ ] Run the tests with 500-1000 concurrent users.
- [ ] Write up a report of issues in HackMD.
- [ ] Decide which ones need to be fixed before launch and create GitHub issues (collaborate with @kgodey)

## Additional context

- [Ask HN: How much traffic to expect if your project hits HN front page? (2014)](https://news.ycombinator.com/item?id=8107658)

**Comment by dmos62** [comment] 2023-02-13 12:42
> Write some load tests that simulate API usage for common activities (logging in, creating schemas, table actions, etc.)

Would it make sense to simulate not only API usage, but the loading of static assets and Django views as well?

**Comment by kgodey** [comment] 2023-02-13 14:56
@dmos62 Yes, but I would do APIs first, make sure that's working well, and then add on static assets and Django views. That way we do it incrementally.

**Comment by dmos62** [comment] 2023-02-14 16:22
Brief update, while I'm working on more definite results: demo server struggling to serve more than ~3 concurrent users.

**Comment by dmos62** [comment] 2023-02-28 17:24
Closing as duplicate of https://github.com/centerofci/mathesar/issues/2547

**Closed by dmos62** 2023-02-28 17:24 UTC
Labels: type: enhancement, work: infrastructure, status: ready
