### ISSUE TITLE
Clicking anywhere on the modal to create new linked table from selected columns closes the modal making it impossible to use

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1750] opened 2022-10-03 19:29 UTC
## Description
* Select a few columns (more than 1)
* Click 'New linked table from columns' in table inspector. The modal opens.
* Click on the Text input for entering name, notice that the modal immediately closes.
* This happens for 'Move columns to existing linked table' option as well.

https://user-images.githubusercontent.com/11850603/193662144-10ce70a4-81ca-4ec8-b504-a0612ec1ab01.mov

**Comment by seancolsen** [comment] 2022-10-03 21:50
I suspect this is a duplicate of #1717

**Closed** 2022-11-09 21:16 UTC
Labels: type: bug, work: frontend, status: ready
