### ISSUE TITLE
Allow the front end to add rows to a table with a PK column that has no dynamic default

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2124] opened 2022-12-19 22:15 UTC
## Current behavior

- If the PK column in a table has a dynamic default, then the user is able to add new rows just fine.

- If the PK column in a table has `null` as its default, then the user gets stuck in this state when attempting to add a new row

    ![image](https://user-images.githubusercontent.com/42411/208536463-2de9fed7-5350-4d42-9742-5c48b3026fe9.png)

    Here, the front end is performing client-side validation before sending an API request to create the record, and seeing that the `id` column defaults to `null` but has a not-NULL constraint (by virtue of having a primary key). The front end also prohibits editing PK cells. So the user is stuck without the ability to enter a new value into the `id` cell.

## Desired behavior

- The user can enter a new value into the PK cell when creating the record.
- After the record is created, the user can no longer edit the PK cell value.

**Comment by pavish** [comment] 2022-12-20 09:17
I believe this is a duplicate of https://github.com/centerofci/mathesar/issues/1356

**Closed** 2022-12-20 09:18 UTC
Labels: type: enhancement, work: frontend, status: ready
