### ISSUE TITLE
Use non-breaking spaces after icons in our NameWithIcon component

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2134] opened 2022-12-20 17:19 UTC
## Problem

Look at this purple box within the "Move Columns" modal.

https://user-images.githubusercontent.com/42411/208725589-8d28b93c-4f96-418d-9c71-10a16fe33077.mp4

The column names are rendered using the NameWithIcon component, and they have `truncate={false}` so they render inline. This works well, except that the line is able to break between the icon and the column name, leaving the icon on its own line.

## Solution

- When rendering NameWithIcon, we should use `&nbsp;` instead of spaces between the icon and the text.
- The non-breaking space should also go between the icons if there are multiple icons.
- We should do this regardless of the value of `truncate`.

## Challenges

- This [long-standing Svelte issue](https://github.com/sveltejs/svelte/issues/189) makes it somewhat difficult to address this problem. We'll need to do some research and be clever about how we handle this. That ticket seems to have a number of suggested work-around techniques.

**Comment by IamEzio** [comment] 2023-02-12 04:48
@seancolsen I'd like to work on this issue. Thanks!

**Comment by Anish9901** [comment] 2023-02-13 08:23
@IamEzio assigned to you. Thanks.

**Comment by IamEzio** [comment] 2023-02-13 17:40
Hi @seancolsen @Anish9901! I did some research regarding the cause of this issue. Turns out that the space between the icon and the text is due to the default nature of `span` tags and not due to an added space.
I followed this [thread on Stackoverflow](https://stackoverflow.com/questions/25667401/how-to-remove-the-space-between-two-span-tags) to find some possible solutions and tried the most upvoted ones. They do remove the space between the icon and text but the line still breaks between them on small screen sizes -- which is our actual problem. I am still looking for possible solutions. If you have one in mind, please point it to me. Thanks!

**Comment by Anish9901** [comment] 2023-03-14 17:19
Unassigned due to inactivity.

**Comment by charvimehradu** [comment] 2023-03-14 17:21
I'm interested in working on this issue. Please assign this issue to me if there's no progress.

**Comment by Anish9901** [comment] 2023-03-14 17:23
Assigned to you @charvimehradu. Thanks!

**Closed** 2023-04-03 14:24 UTC
Labels: type: enhancement, work: frontend, status: ready
