### ISSUE TITLE
"docker compose" does not create the `.volumes` directory

### ISSUE THREAD

**Issue by dhruvkb** [centerofci/mathesar#175] opened 2021-06-03 05:57 UTC
**Describe the bug**
The setup instructions are missing the step for creating the `.volumes` directory inside the root of the repo before running `docker-compose up`. This directory is being used to bind the PostgreSQL data folder but is not automatically created by Docker Compose

**Expected behavior**
`docker-compose up` should just work out-of-the-box.

**To Reproduce**

- Set up Docker and Docker Compose.
- Clone the repo and `cd` into it.
- Run `docker-compose up`.

**Environment**
 - OS: MacOS
 - Other info:
   - Docker version: 20.10.6, build 370c289

**Additional context**
This can be resolved by either adding a blank `.volumes/` directory with a Git keep file or by adding a step to make this directory in the instructions.

**Comment by mathemancer** [comment] 2021-06-03 08:55
@kgodey can you confirm this issue?  This isn't a problem on my machine (i.e., the `.volumes/` directory is created automatically as expected after running `docker-compose up`).  Perhaps it has something to do with the way MacOS uses a VM for the docker kernel; I'm using linux, and docker is a bit "closer to the metal" in that environment.  

If possible, I'd rather be able to solve this so that it's actually automatically created for all users as expected, rather than adding a stub or instruction.

**Comment by kgodey** [comment] 2021-06-03 11:35
@dhruvkb I'm unable to reproduce this. I deleted the repo and all Docker images, re-cloned the repo, `docker-compose up` works fine and creates the `.volumes/` folder automatically.

I'm on macOS 10.14.6 and using Docker version 20.10.5, build 55c4c88.

**Comment by dhruvkb** [comment] 2021-06-03 14:22
Okay, I figured out the cause of the error. The setup as expected works with `docker-compose up` which creates the directory automatically and all is well. But the `docker compose` command (without the hyphen, basically Compose but now a part of the Docker CLI itself) does not automatically create missing directories and fails to start.

<img width="1082" alt="Screenshot 2021-06-03 at 7 51 13 PM" src="https://user-images.githubusercontent.com/16580576/120660551-0fe13f00-c4a5-11eb-8aa4-465a59497e10.png">

**Comment by kgodey** [comment] 2021-06-03 14:24
Thanks @dhruvkb, I've marked this as ready for work.

**Comment by dhruvkb** [comment] 2021-06-09 05:28
Now that we know it's a difference of `docker-compose` and the new Compose CLI, let's get this fixed at the cause: docker/compose-cli#1764

**Comment by kgodey** [comment] 2021-06-09 11:54
@dhruvkb Makes sense, I'll mark this issue as blocked until the Compose CLI bug is fixed.

**Comment by dhruvkb** [comment] 2021-06-10 01:20
Verified that the issue is fixed in the Compose CLI v2 (https://github.com/docker/compose-cli/issues/1764#issuecomment-857644310). We can close the ticket.

**Comment by kgodey** [comment] 2021-06-10 10:14
@dhruvkb thanks!

**Closed by kgodey** 2021-06-10 10:14 UTC
Labels: status: blocked, type: bug, work: infrastructure
