### ISSUE TITLE
Breadcrumb link text is not visible when summary is NULL

### ISSUE THREAD

**Issue by ghislaineguerin** [centerofci/mathesar#2160] opened 2022-12-22 14:35 UTC
### Problem
Navigate to the record page, where the record has a NULL summary.
Observe the text color of the breadcrumb link.

### Screenshot
<img width="517" alt="image" src="https://user-images.githubusercontent.com/845767/209157078-f2bc6f0d-f8c9-44bb-abb0-ed8841921679.png">

**Comment by ghislaineguerin** [comment] 2022-12-22 15:11
@seancolsen here's the ticket for NULL record summaries

**Comment by seancolsen** [comment] 2022-12-22 15:31
Duplicate of #2055

**Closed by seancolsen** 2022-12-22 15:31 UTC
Labels: type: bug, work: frontend, status: triage
