### ISSUE TITLE
Visual distinction between Table Inspector and table vanishes when inspector overlaps cells

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1621] opened 2022-09-09 18:52 UTC
## Reproduce

- When the sheet does not consume the full width of its allocated space on the page, I see a drop shadow on the left of the Table Inspector

- But when the Table Inspector overlaps the sheet cells, that drop shadow disappears.

![Peek 2022-09-09 14-48](https://user-images.githubusercontent.com/42411/189422701-6e54acd8-51e5-4bcf-b22a-cd107518d485.gif)

CC @rajatvijay

**Comment by seancolsen** [comment] 2022-09-14 17:21
I'm keeping this in Cycle 4 because it will be visible in the demo video on a number of screens.

**Comment by rajatvijay** [comment] 2022-09-22 08:34
@seancolsen this seems to be working fine for me. I checked in multiple browsers too

<img width="872" alt="Screenshot 2022-09-22 at 2 03 52 PM" src="https://user-images.githubusercontent.com/11032856/191698986-6d60273c-0f11-453a-824b-7e94ee54e78c.png">

Is there a specific way to reproduce this?

**Closed** 2022-09-22 11:13 UTC
Labels: type: enhancement, work: frontend, restricted: maintainers, status: review
