### ISSUE TITLE
Blank Error while creating new schema in live demo

### ISSUE THREAD

**Issue by Muhammad-Ahsan-Rasheed** [centerofci/mathesar#2700] opened 2023-03-17 10:41 UTC
## Description
I created a new schema without following the guideline. It throw the error but with blank message.

## Expected behavior
It should throw the error like "Name is not according to format."

## To Reproduce
Error can be reproduced if anyone creates a schema with names like Test etc. 

## Environment
 - OS: (Windows)
 - Browser: (Chrome)
 - Browser Version: (111.0.5563.65)
 - Other info:

## Additional context
![image](https://user-images.githubusercontent.com/69692532/225882617-50636845-bec0-4046-9959-fe021a3cb401.png)

**Comment by pavish** [comment] 2023-03-17 10:48
@Muhammad-Ahsan-Rasheed Could you please check your network tab in the browser's development console and provide the error thrown when the request is made?

**Comment by Muhammad-Ahsan-Rasheed** [comment] 2023-03-17 14:28
@pavish Hi, nothing came up.

**Comment by kgodey** [comment] 2023-03-17 19:13
@Muhammad-Ahsan-Rasheed what schema name did you use?

**Comment by rajatvijay** [comment] 2023-03-20 16:51
Marking this as `draft` since we do not have enough info to reproduce this and work on it.

**Comment by Muhammad-Ahsan-Rasheed** [comment] 2023-03-20 18:50
> @Muhammad-Ahsan-Rasheed what schema name did you use?

I named it as Test. I mentioned in **to Reproduce**, sorry for the late response.

**Comment by kgodey** [comment] 2023-03-20 21:19
I cannot reproduce this issue. I created a schema called "Test" in the demo server and it worked fine. @Muhammad-Ahsan-Rasheed would you be able to try again?

**Comment by dmos62** [comment] 2023-07-04 14:04
Cannot reproduce either. Closing. @Muhammad-Ahsan-Rasheed reopen if you're still able to reproduce.

**Closed by dmos62** 2023-07-04 14:04 UTC
Labels: type: bug, work: backend, work: infrastructure, status: draft, restricted: maintainers, user reported
