### ISSUE TITLE
Validate the constraint used for moving the columns between related tables

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#1881] opened 2022-11-01 18:24 UTC
## Problem

#1878 adds a parameter `relation_fk_constraint` to the `/tables/<id>/move_columns/` API, but the constraint sent by the client is not validated correctly to throw an error
- If the constraint is not a foreign key constraint
- If the foreign key constraint does not link the `source table` and the `target table`

## Proposed solution
Add validation to validate the above cases and throw the correct error.

**Comment by dmos62** [comment] 2023-03-21 11:48
Undrafting, since work seems well defined.

Also, marking as good first issue. For anyone that picks this up, note that this was submitted a few months back and we may already have fixed this, so reproducing should be step 1.

**Comment by ShailRT** [comment] 2023-03-30 00:38
@dmos62 @silentninja Is this still available because I don't see any `relation_fk_constraint` in `db/tables/operations/move_columns.py`

**Comment by dmos62** [comment] 2023-03-30 09:49
@ShailRT no, there's been a mistake. This issue was created while the referenced PR was still not merged and it got killed, but this issue stayed and I didn't notice when I marked this issue as ready.

I'm closing it. Sorry for the inconvenience.

**Closed by dmos62** 2023-03-30 09:49 UTC
Labels: type: enhancement, good first issue, help wanted, work: backend, status: ready
